name: cli-wallet-android

on:  
  pull_request:
    branches: [ main ]

jobs:    
  maestro-cloud:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: wallets/rn_cli_wallet
    outputs:
      app: app/build/outputs/apk/release
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'
          cache: gradle      
      - run: touch .env && echo "ENV_PROJECT_ID=${{ secrets.ENV_PROJECT_ID }}\nENV_RELAY_URL=${{ secrets.ENV_RELAY_URL }}\nENV_SENTRY_DSN=${{ secrets.W3W_SENTRY_DSN }}" >> .env
      - run: touch ./android/sentry.properties && echo "${{ secrets.W3W_SENTRY_FILE }}" >> ./android/sentry.properties
      - run: npm install -g yarn
      - run: yarn
      - run: yarn android:build
      - uses: mobile-dev-inc/action-maestro-cloud@v1
        with:
          api-key: ${{ secrets.MAESTRO_CLOUD_API_KEY }}
          app-file: wallets/rn_cli_wallet/android/app/build/outputs/apk/release/app-release.apk
