name: release-android-walletkit-internal

permissions:
  id-token: write
  contents: read

on: workflow_dispatch

jobs:
  release-internal:
    uses: ./.github/workflows/release-android-base.yaml
    with:
      name: WalletKit React Native
      root-path: 'wallets/rn_cli_wallet'
      release-type: 'internal'
      project-type: 'wallet'
      output-path: 'wallets/rn_cli_wallet/android/app/build/outputs/apk/internal/app-internal.apk'
      upload-to-bucket: true
    secrets:
      project-id: ${{ vars.WALLETKIT_PROJECT_ID }}
      relay-url: ${{ secrets.ENV_RELAY_URL }}
      sentry-dsn: ${{ secrets.W3W_SENTRY_DSN }}
      sentry-file: ${{ secrets.W3W_SENTRY_FILE }}
      pay-api-key: ${{ secrets.ENV_PAY_API_KEY }}
      secrets-file: ${{ secrets.ANDROID_SECRETS_FILE }}
      firebase-app-id: ${{ secrets.W3W_ANDROID_INTERNAL_FIREBASE_APP_ID }}
      gsa-key: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
      keystore-name: ${{ secrets.WC_INTERNAL_KEYSTORE_NAME }}
      keystore: ${{ secrets.WC_INTERNAL_KEYSTORE }}
      google-services-file: ${{ secrets.ANDROID_GOOGLE_SERVICES_BASE64 }}
      aws-account-id: ${{ secrets.AWS_ACCOUNT_ID }}
      slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
      firebase-url: ${{ vars.FIREBASE_WALLETKIT_INTERNAL_URL }}
