name: release-android-appkit-internal

permissions:
  id-token: write
  contents: read

on: workflow_dispatch

jobs:
  release-internal:
    uses: ./.github/workflows/release-android-base.yaml
    with:
      name: AppKit React Native
      root-path: 'dapps/W3MWagmi'
      release-type: 'internal'
      project-type: 'dapp'
      output-path: 'dapps/W3MWagmi/android/app/build/outputs/apk/internal/app-internal.apk'
      upload-to-bucket: true
    secrets:
      env-file: ${{ vars.APPKIT_ENV_FILE }}
      sentry-file: ${{ secrets.W3M_WAGMI_SENTRY_FILE }}
      secrets-file: ${{ secrets.ANDROID_SECRETS_FILE }}
      firebase-app-id: ${{ secrets.W3M_WAGMI_ANDROID_INTERNAL_FIREBASE_APP_ID }}
      gsa-key: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
      keystore-name: ${{ secrets.WC_INTERNAL_KEYSTORE_NAME }}
      keystore: ${{ secrets.WC_INTERNAL_KEYSTORE }}
      aws-account-id: ${{ secrets.AWS_ACCOUNT_ID }}
      slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
      firebase-url: ${{ vars.FIREBASE_APPKIT_INTERNAL_URL }}